### PR TITLE
[DO NOT MERGE] placeholder PR to run tests on release

### PR DESCRIPTION
**Pull request by tomasatdatabricks**
Run tests on release

### CODE REVIEW

**Comment by sueann** [comment]
These changes are in the release 0.3.0 but not in master, right? Can we merge this so we master is consistent please.

**Comment by tomasatdatabricks** [comment]
The only change that is here and not in master is  bumping the version to 0.3.0 in the build.sbt.
Otherwise there was a cherry-pick of Sid's commit from master and I've added missing encoding specification in the keras_applications.py file (also in master).

If you want to update the version in build.sbt it's probably easier to do that explicitly in a separate PR rather than rebasing/merging this one.

**Comment by sueann** [comment]
Ah ok. Can you create a quick PR? Thanks!

**Comment by tomasatdatabricks** [comment]
Done, see https://github.com/databricks/spark-deep-learning/pull/98.

I am gonna close this one after the other PR gets merged..

**Pull request closed without merging**
